//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoRestaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoSucursal
    {
        public int ContactoSucursalID { get; set; }
        public string E_mail { get; set; }
        public string Contacto { get; set; }
        public string Telefono { get; set; }
        public int FKSucursalID { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
    }
}
