//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoRestaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int CuentaID { get; set; }
        public string Usuario { get; set; }
        public string Contrasenia { get; set; }
        public Nullable<int> Activo { get; set; }
        public int FKUsuarioID { get; set; }
    
        public virtual Usuario Usuario1 { get; set; }
    }
}
