//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoRestaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valoracion
    {
        public int ValoracionID { get; set; }
        public int Valor { get; set; }
        public int FKTipoDeValoracionID { get; set; }
        public int FKSucursalID { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoDeValoracion TipoDeValoracion { get; set; }
    }
}
